# Generated by Django 5.1.7 on 2025-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_post_options_remove_post_repost_of_post_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('repost', 'Repost'), ('quote', 'Quote')], default='post', max_length=6),
        ),
    ]
