# Generated by Django 5.1.7 on 2025-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0005_alter_notifications_comment_alter_notifications_post'),
        ('Posts', '0006_alter_post_options_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('repost', 'Repost'), ('quote', 'Quote'), ('reply', 'Reply')], default='post', max_length=6),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
