# Generated by Django 5.1.7 on 2025-03-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Customizables',
        ),
    ]
