# Generated by Django 5.1.7 on 2025-03-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_iamge',
            new_name='profile_image',
        ),
    ]
