# Generated by Django 5.1.7 on 2025-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
