# Generated by Django 5.1.7 on 2025-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_remove_profile_name_profile_blocked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_iamge',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
