# Generated by Django 5.1.7 on 2025-04-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_profile_cover_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cover_iamge',
            new_name='cover_image',
        ),
    ]
