# Generated by Django 5.1.7 on 2025-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friendship', '0003_friendrequest_updated_at_alter_friendrequest_to_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
