# Generated by Django 5.1.7 on 2025-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('friend_request', 'Friend Request'), ('new_post', 'New Post'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('comment_like', 'Comment Like'), ('comment_reply', 'Comment Reply')], max_length=20, null=True),
        ),
    ]
