# Generated by Django 5.1.7 on 2025-03-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friendship', '0002_remove_friendrequest_accepted_friendrequest_status'),
        ('Notifications', '0002_alter_notifications_notification_type'),
        ('Posts', '0002_remove_media_duration_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Friendship.friendrequest'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post'),
        ),
    ]
