# Generated by Django 5.1.7 on 2025-03-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_notifications_friend_request_notifications_post'),
        ('Posts', '0002_remove_media_duration_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.comment'),
        ),
    ]
