# Generated by Django 5.1.7 on 2025-05-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0004_notifications_comment'),
        ('Posts', '0006_alter_post_options_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='Posts.post'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='Posts.post'),
        ),
    ]
