# Generated by Django 5.1.7 on 2025-06-12 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0006_alter_notifications_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('new_post', 'New Post'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('comment_like', 'Comment Like'), ('comment_reply', 'Comment Reply')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='target_object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
