# Generated by Django 5.1.7 on 2025-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0007_alter_notifications_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('new_post', 'New Post'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('comment_like', 'Comment Like'), ('comment_reply', 'Comment Reply'), ('post_repost', 'Post Repost'), ('post_quote', 'Post Quote')], max_length=20),
        ),
    ]
