# Generated by Django 5.1.7 on 2025-06-13 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0008_alter_notifications_notification_type'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['to_user', 'active', '-created_at'], name='Notificatio_to_user_a7296d_idx'),
        ),
    ]
